apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenddeployment
  namespace: frontendmern
spec:
  selector:
    matchLabels:
      app: mernmicro
  template:
    metadata:
      labels:
        app: mernmicro
    spec:
      containers:
      - name: frontenddeployment
        image: public.ecr.aws/f8g8h5d4/rmernmicrof:frontend
        env:
        - name: REACT_APP_BACKEND_HELLO_URL
          valueFrom:
            configMapKeyRef:
              name: fe-config
              key: REACT_APP_BACKEND_HELLO_URL
        - name: REACT_APP_BACKEND_PROFILE_URL
          valueFrom:
            configMapKeyRef:
              name: fe-config
              key: REACT_APP_BACKEND_PROFILE_URL
        ports:
        - containerPort: 3000
