apiVersion: v1
kind: Secret
metadata:
  name: profile-secret
  namespace: {{ .Values.beprofile.namespace }}
data:
  MONGO_URI: {{ .Values.beprofile.env.MONGO_URL | b64enc }}
type: Opaque
# "mongodb://ravikishan:Cluster0@cluster0.y9zohpu.mongodb.net:27017/sampleNginxLB"