apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-config
  namespace: {{ .Values.frontend.namespace }}
  labels:
    app: mernmicro
data:
  REACT_APP_BACKEND_HELLO_URL: "{{ .Values.frontend.data.REACT_APP_BACKEND_HELLO_URL }}"
  REACT_APP_BACKEND_PROFILE_URL: "{{ .Values.frontend.data.REACT_APP_BACKEND_PROFILE_URL }}"
