apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenddeployment
  namespace: {{ .Values.frontend.namespace }}
spec:
  selector:
    matchLabels:
      app: mernmicro
  template:
    metadata:
      labels:
        app: mernmicro
    spec:
      containers:
      - name: frontenddeployment
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        env:
        - name: REACT_APP_BACKEND_HELLO_URL
          valueFrom:
            configMapKeyRef:
              name: fe-config
              key: REACT_APP_BACKEND_HELLO_URL
        - name: REACT_APP_BACKEND_PROFILE_URL
          valueFrom:
            configMapKeyRef:
              name: fe-config
              key: REACT_APP_BACKEND_PROFILE_URL
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
