apiVersion: v1
kind: Service
metadata:
  name: frontendservice
  namespace: {{ .Values.frontend.namespace }}
spec:
  selector:
    app: mernmicro
  ports:
  - protocol: {{ .Values.behello.ports.protocol }}
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
